Fix whitespace issues, new fix-whitespace script and pre-commit hook.
For sources use tabs instead of spaces, strip trailing whitespace
(i. e., kernel formatting conventions ).

All other files (besides Makefile*) uses space for indentation and
also strips trailing whitespace. Fix occasional occurrences of
explicit tabs in shell script search patterns etc.

Add a pre-commit hook which fixes this if installed as
.git/hooks/pre-commit (use git commit --no-verify to disable).

The fix-whitespace filter can be used as a tree-filter to
enforce rules on garbled trees.

diff --git a/contrib/lircs b/contrib/lircs
--- a/contrib/lircs
+++ b/contrib/lircs
@@ -31,104 +31,104 @@ FILE_EDITOR=vim
 # function declarations
 
 start_clients () {
-	if [ -s ${CONFIG_FILE} ]; then
-		echo -n Starting LIRC clients ...
+        if [ -s ${CONFIG_FILE} ]; then
+                echo -n Starting LIRC clients ...
 
-		# add more clients HERE or change the ones I put here as a start
-		irxevent &
-		irexec --daemon
+                # add more clients HERE or change the ones I put here as a start
+                irxevent &
+                irexec --daemon
 
-		echo " done"
-	else
-		echo "LIRC config file not found in ${CONFIG_FILE}"
-		exit 1
-	fi
+                echo " done"
+        else
+                echo "LIRC config file not found in ${CONFIG_FILE}"
+                exit 1
+        fi
 }
 
 restart_lircd () {
-	if [ "${USER}" = "root" ]; then
-		# change this if your Linux system keeps the init scripts elsewhere
-		/sbin/init.d/lircd restart
-	else
-		echo "`basename ${0}`: you must be 'root' to restart the LIRC daemon (lircd)."
-		exit 1
-	fi
+        if [ "${USER}" = "root" ]; then
+                # change this if your Linux system keeps the init scripts elsewhere
+                /sbin/init.d/lircd restart
+        else
+                echo "`basename ${0}`: you must be 'root' to restart the LIRC daemon (lircd)."
+                exit 1
+        fi
 }
 
 stop_lircd () {
-	if [ "${USER}" = "root" ]; then
-		# change this if your Linux system keeps the init scripts elsewhere
-		/sbin/init.d/lircd stop
-	else
-		echo "`basename ${0}`: you must be 'root' to stop the LIRC daemon (lircd)."
-		exit 1
-	fi
+        if [ "${USER}" = "root" ]; then
+                # change this if your Linux system keeps the init scripts elsewhere
+                /sbin/init.d/lircd stop
+        else
+                echo "`basename ${0}`: you must be 'root' to stop the LIRC daemon (lircd)."
+                exit 1
+        fi
 }
 
 edit_config_file () {
-	${FILE_EDITOR} ${CONFIG_FILE}
+        ${FILE_EDITOR} ${CONFIG_FILE}
 }
 
 print_info () {
-	echo "LIRC starter version 0.2, 09/2000 "
-	echo "Written by Michael Kammerer <M.Kammerer@gmx.de>."
-	echo "Visit 'www.crosswinds.net/~michaelkammerer/lircs' for updates."
+        echo "LIRC starter version 0.2, 09/2000 "
+        echo "Written by Michael Kammerer <M.Kammerer@gmx.de>."
+        echo "Visit 'www.crosswinds.net/~michaelkammerer/lircs' for updates."
 }
 
 print_help () {
-	echo "LIRC starter usage: lirc [option]"
-	echo "'option' can be:"
-	echo "as any user:"
-	echo "-h | --help     print this short help text"
-	echo "-c | --clients  start LIRC clients (necessary if lircd was restarted)"
-	echo "-e | --edit     edit LIRC config file '${CONFIG_FILE}'"
-	echo "-v | --version  print script version and other info"
-	echo "only as 'root':"
-	echo "-r | --restart  restart LIRC daemon (lircd) "
-	echo "-s | --stop     stop LIRC daemon"
+        echo "LIRC starter usage: lirc [option]"
+        echo "'option' can be:"
+        echo "as any user:"
+        echo "-h | --help     print this short help text"
+        echo "-c | --clients  start LIRC clients (necessary if lircd was restarted)"
+        echo "-e | --edit     edit LIRC config file '${CONFIG_FILE}'"
+        echo "-v | --version  print script version and other info"
+        echo "only as 'root':"
+        echo "-r | --restart  restart LIRC daemon (lircd) "
+        echo "-s | --stop     stop LIRC daemon"
 }
 
 
 # processing of command line arguments
 
 case $1 in
-	-r)
-		restart_lircd
-		;;
-	--restart)
-		restart_lircd
-		;;
-	-s)
-		stop_lircd
-		;;
-	--stop)
-		restart_lircd
-		;;
-	-c)
-		start_clients
-		;;
-	--clients)
-		start_clients
-		;;
-	-h)
-		print_help
-		;;
-	--help)
-		print_help
-		;;
-	-e)
-		edit_config_file
-		;;
-	--edit)
-		edit_config_file
-		;;
-	-v)
-		print_info
-		;;
-	--version)
-		print_info
-		;;
-	*)
-		print_help
-		;;
+        -r)
+                restart_lircd
+                ;;
+        --restart)
+                restart_lircd
+                ;;
+        -s)
+                stop_lircd
+                ;;
+        --stop)
+                restart_lircd
+                ;;
+        -c)
+                start_clients
+                ;;
+        --clients)
+                start_clients
+                ;;
+        -h)
+                print_help
+                ;;
+        --help)
+                print_help
+                ;;
+        -e)
+                edit_config_file
+                ;;
+        --edit)
+                edit_config_file
+                ;;
+        -v)
+                print_info
+                ;;
+        --version)
+                print_info
+                ;;
+        *)
+                print_help
+                ;;
 esac
