git-tools, build: Update formatting tools.
Remove all stuff in pre-commit which modifies sources, instead just
check them. Use checkpatch.pl to verify source formatting (through
checkfiles wrapper.

diff --git a/git-tools/pre-commit b/git-tools/pre-commit
--- a/git-tools/pre-commit
+++ b/git-tools/pre-commit
@@ -1,29 +1,44 @@
 #!/bin/bash
 #
-# lirc pre-commit hook: remove trailing space, use tabs for indent.
+# lirc pre-commit hook: Check source formatting, last update: in manpages
+# and overall whitespace.
 
-C_SOURCES=( $( git diff --cached --name-status | \
-              grep -v ^D | awk '$1 $2 { print $2}' | grep -e '\.c$|\.h$' ))
+function files_to_update()
+{
+    git diff --cached --name-status | grep -v ^D | awk '$1 $2 { print $2}'
+}
 
-OTHERS=( $( git diff --cached --name-status | \
-              grep -v ^D | awk '$1 $2 { print $2}' | \
-              grep -Ev  '\.c$|\.h$|\.png$|\.gif$|\.jpg$|Makefile'))
 
-MAN_SOURCES=( $( git diff --cached --name-status | \
-              grep -v ^D | awk '$1 $2 { print $2}' | \
-              grep -E  '\.1$|\.5$|\.8$'))
+here=$(dirname $(readlink -fn $0))
 
+C_SOURCES=( $( files_to_update | grep -E '\.c$|\.h$'))
+
+MAN_SOURCES=( $( files_to_update |  grep -E  '\.1$|\.4|\.5$|\.8$'))
+
+
+# See that C sources passes checkfile (i. e., checkpatch.pl)
 for f in ${C_SOURCES[@]} ; do
-       test -L $f && continue
-       unexpand $f | sed -r 's/[ \t]+$//' > $f.tmp && mv -f $f.tmp $f
-done
-for f in ${OTHERS[@]} ; do
-       test -L $f && continue
-       expand $f | sed -r 's/[ \t]+$//' > $f.tmp && \
-           cat $f.tmp > $f && rm $f.tmp
+    test -L $f && continue
+    if ! $here/checkfiles $f; then
+        echo "Checkpatch errors, fix them (or use --no-verify to commit anyway)."
+        exit 1
+    fi
 done
 
-if test -n "$MAN_SOURCES"; then
-    now=$( date +"%b %Y" )
-    sed -i '/Last change:/s/:.*20../'": $now/" $MAN_SOURCES
-fi
+# Check that Last Update: is sane in manpages.
+now=$( date +"%b %Y" )
+for f in ${MAN_SOURCES[@]} ; do
+    test -L $f && continue
+    sed  '/Last change:/s/:.*20../'": $now/" $f > $f.tmp
+    diff=$(diff -b -q $f $f.tmp)
+    if [ -n "$diff" ]; then
+        echo "Please update \"Last change\" in $f (or use --no-verify)"
+        rm $f.tmp
+	exit 1
+    else
+        rm $f.tmp
+    fi
+done
+
+# If there are whitespace errors, print the offending file names and fail.
+exec git diff-index --check --cached HEAD --
